-- Generated by Mocodo 4.2.11

CREATE TABLE AMATEUR (
  Nom_1           VARCHAR(42),
  Theme           VARCHAR(42),
  Description     VARCHAR(42),
  Annee_de_sortie VARCHAR(42),
  Dimensions      VARCHAR(42),
  Nom_2           VARCHAR(42),
  Licence         VARCHAR(42)
);

CREATE TABLE Assemblage (
  PRIMARY KEY (Titre_1, Titre_2),
  Titre_1 VARCHAR(42) NOT NULL,
  Titre_2 VARCHAR(42) NOT NULL
);

CREATE TABLE BOITE (
  PRIMARY KEY (Reference),
  Reference VARCHAR(42) NOT NULL,
  nom       VARCHAR(42),
  prix      VARCHAR(42)
);

CREATE TABLE CONFIGURATION (
  PRIMARY KEY (Propriete),
  Propriete   VARCHAR(42) NOT NULL,
  Valeur      VARCHAR(42),
  Propriete_2 VARCHAR(42) NOT NULL
);

CREATE TABLE ETAPE (
  PRIMARY KEY (Titre, Numero),
  Titre        VARCHAR(42) NOT NULL,
  Numero       VARCHAR(42) NOT NULL,
  Image        VARCHAR(42),
  Instructions VARCHAR(42)
);

CREATE TABLE JOUEUSE (
  PRIMARY KEY (Prenom),
  Prenom             VARCHAR(42) NOT NULL,
  Date_d_inscription VARCHAR(42),
  Avatar             VARCHAR(42),
  Date_deb           VARCHAR(42) NULL
);

CREATE TABLE OFFICIEL (
  Nom             VARCHAR(42),
  Theme           VARCHAR(42),
  Description     VARCHAR(42),
  Annee_de_sortie VARCHAR(42),
  Dimensions      VARCHAR(42),
  Age_recommande  VARCHAR(42),
  Ville           VARCHAR(42) NOT NULL
);

CREATE TABLE PARTIE (
  PRIMARY KEY (Date_deb),
  Date_deb  VARCHAR(42) NOT NULL,
  Date_fin  VARCHAR(42),
  Score     VARCHAR(42),
  Gagnante  VARCHAR(42),
  Propriete VARCHAR(42) NOT NULL
);

CREATE TABLE piece (
  PRIMARY KEY (Titre),
  Titre               VARCHAR(42) NOT NULL,
  Description         VARCHAR(42),
  Chemin_vers_fichier VARCHAR(42),
  id_serial           VARCHAR(42),
  longueur            VARCHAR(42),
  largeur             VARCHAR(42),
  hauteur             VARCHAR(42),
  couleur             VARCHAR(42),
  Ville               VARCHAR(42) NOT NULL,
  Date                VARCHAR(42),
  Quantite            VARCHAR(42),
  id                  VARCHAR(42) NOT NULL
);

CREATE TABLE SUBSTITUTION (
  PRIMARY KEY (id),
  id          VARCHAR(42) NOT NULL,
  nom         VARCHAR(42),
  commentaire VARCHAR(42)
);

CREATE TABLE TOURS (
  PRIMARY KEY (Date_deb, Numero),
  Date_deb           VARCHAR(42) NOT NULL,
  Numero             VARCHAR(42) NOT NULL,
  Prenom             VARCHAR(42),
  Date_d_inscription VARCHAR(42),
  Titre              VARCHAR(42) NOT NULL,
  Description        VARCHAR(42),
  Action             VARCHAR(42)
);

CREATE TABLE USINE (
  PRIMARY KEY (Ville),
  Ville VARCHAR(42) NOT NULL,
  Pays  VARCHAR(42)
);

ALTER TABLE Assemblage ADD FOREIGN KEY (Titre_2) REFERENCES piece (Titre);
ALTER TABLE Assemblage ADD FOREIGN KEY (Titre_1) REFERENCES PHOTO (Titre);

ALTER TABLE CONFIGURATION ADD FOREIGN KEY (Propriete_2) REFERENCES CONFIGURATION (Propriete);

ALTER TABLE ETAPE ADD FOREIGN KEY (Titre) REFERENCES PHOTO (Titre);

ALTER TABLE JOUEUSE ADD FOREIGN KEY (Date_deb) REFERENCES PARTIE (Date_deb);

ALTER TABLE OFFICIEL ADD FOREIGN KEY (Ville) REFERENCES USINE (Ville);

ALTER TABLE PARTIE ADD FOREIGN KEY (Propriete) REFERENCES CONFIGURATION (Propriete);

ALTER TABLE piece ADD FOREIGN KEY (id) REFERENCES SUBSTITUTION (id);
ALTER TABLE piece ADD FOREIGN KEY (Ville) REFERENCES USINE (Ville);

ALTER TABLE TOURS ADD FOREIGN KEY (Titre) REFERENCES piece (Titre);
ALTER TABLE TOURS ADD FOREIGN KEY (Date_deb) REFERENCES PARTIE (Date_deb);
